import Head from 'next/head';
import Link from 'next/link';

const Layout = ({children, title ="currentcrypt"}) => {
    return (
        <div className="layout">
            <Head>
                <title> {title} </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="header">
                <Link href="/" passHref>
                    <a>
                        <h2 className="logo-crypto">Logo Goes Here</h2>
                    </a>
                </Link>
            </header>
            <main>{children}</main>
        </div>
    )
};

export default Layout;